import PDFDocument from "pdfkit";
import { getModel } from "../utils/model.js";
import fs from "fs";
import { uploadToCloudinary } from "../utils/uploadToCloudinary.js";
import { checkAgentLimit } from "../config/agentRateLimit.js";
import { deductCredits } from "../utils/deductCredits.js";

export const pdfAgent = async (state) => {

  try {
//await checkAgentLimit(
   // state.userId,
   // "pdf"
  //);
 //await deductCredits(

       // state.userId,

        //"pdf"

    //);  
    const llm =
      getModel("pdf");

    const aiResponse =
      await llm.invoke(`

Create a professional document about:

${state.prompt}

Rules:

- Generate a professional title.
- Generate introduction.
- Generate multiple sections.
- Generate bullet points where required.
- Generate conclusion.
- No markdown.
- No code blocks.
- No ** symbols.
- No ### headings.
- Return plain text only.

`);

    const rawContent =
      aiResponse?.content?.trim() ||
      state.prompt;

    const lines =
      rawContent
        .split("\n")
        .filter(line => line.trim());

    const generatedTitle =
      lines?.[0]?.length < 120
        ? lines[0]
        : state.prompt;

    const cleanContent =
      rawContent
        .replace(/\*\*/g, "")
        .replace(/```/g, "")
        .replace(/###/g, "")
        .replace(/##/g, "")
        .replace(/#/g, "")
        .trim();

   const safeTitle = generatedTitle
  .replace(/[^\w\s-]/g, "")
  .replace(/\s+/g, "-");

const fileName = `${safeTitle}-${Date.now()}.pdf`;

    const doc =
      new PDFDocument({
        size: "A4",
        margin: 50,
        bufferPages: true,
        info: {
          Title: generatedTitle,
          Author: "WorkBenchAI",
          Subject: state.prompt,
          Creator: "WorkBenchAI PDF Agent"
        }
      });

    const chunks = [];

    doc.on("data", chunk => {
      chunks.push(chunk);
    });

    // Cover Title

    doc
      .fontSize(26)
      .fillColor("#111827")
      .text(
        generatedTitle,
        {
          align: "center"
        }
      );

    doc.moveDown();

    doc
      .fontSize(10)
      .fillColor("#6B7280")
      .text(
        `Generated on ${new Date().toLocaleString()}`,
        {
          align: "center"
        }
      );

    doc.moveDown(3);

    // Content

    doc
      .fontSize(12)
      .fillColor("#374151")
      .text(
        cleanContent,
        {
          align: "left",
          lineGap: 6
        }
      );

    doc.moveDown(2);

    doc
      .fontSize(10)
      .fillColor("#9CA3AF")
      .text(
        "Generated by WorkBenchAI",
        {
          align: "center"
        }
      );

    doc.end();

    await new Promise(
      (resolve, reject) => {

        doc.on(
          "end",
          resolve
        );

        doc.on(
          "error",
          reject
        );

      }
    );

    const pdfBuffer =
      Buffer.concat(chunks);
      console.log("PDF Size:", pdfBuffer.length);

fs.writeFileSync("test.pdf", pdfBuffer);

console.log("PDF Saved");

const result = await uploadToCloudinary(
  pdfBuffer,
  "WorkBenchAI/pdf",
  fileName,
  "raw"
);

const downloadUrl = result.secure_url
  .replace(".pdf.pdf", ".pdf")
  .replace("/upload/", "/upload/fl_attachment/");

console.log(result);

    return {

      ...state,

response: `
📄 **${generatedTitle}**

📥 [Download PDF](${downloadUrl})
`.trim()

    };

  } catch (error) {

    console.log(
      "PDF Agent Error:",
      error
    );

    return {

      ...state,

      response:
        "❌ Failed to generate PDF."

    };

  }

};